-- liquibase formatted sql

-- changeset script:1
-- comment: Creation table amparo
create table amparo (
    id integer generated by default as identity,
    nombre varchar(255),
    primary key (id)
);
--
-- changeset script:2
-- comment: Creation table asegurado
create table asegurado (
    id integer generated by default as identity,
    apellido varchar(255),
    fecha_nacimiento date,
    nombre varchar(255),
    numero_identificacion integer,
    id_sexo_pk integer,
    id_tipo_documento_pk integer,
    primary key (id)
);
--
-- changeset script:3
-- comment: Creation table prima
create table prima (
    id integer generated by default as identity,
    edad_maxima integer,
    edad_minima integer,
    porcentaje float(53),
    id_amparo_pk integer,
    primary key (id)
);
--
-- changeset script:4
-- comment: Creation table sexo
create table sexo (
    id integer generated by default as identity,
    tipo varchar(255),
    primary key (id)
);
--
-- changeset script:5
-- comment: Creation table tipo_documento
create table tipo_documento (
    id integer generated by default as identity,
    tipo varchar(255),
    primary key (id)
);
--
-- changeset script:11
-- comment: Creation tipo_documento
insert into tipo_documento (tipo) values
    ( 'CC' ),
    ( 'CE' );
--
-- changeset script:12
-- comment: Creation sexo
insert into sexo (tipo) values
    ( 'Masculino' ),
    ( 'Femenino' );
--
-- changeset script:13
-- comment: Creation amparo
insert into amparo ( nombre ) values
    ( 'Muerte accidental' ),
    ( 'Desmembración' ),
    ( 'Auxilio funerario' ),
    ( 'Renta vitalicia' );

--
-- changeset script:14
-- comment: Creation prima
insert into prima (id_amparo_pk, edad_minima, edad_maxima, porcentaje) values
    ( 1, 18, 45, 0.02304),
    ( 1, 46, 75, 0.02012),
    ( 2, 18, 50, 0.1809),
    ( 2, 51, 70, 0.16043),
    ( 3, 18, 60, 0.14123),
    ( 3, 61, 70, 0.1545),
    ( 4, 18, 50, 0.12123),
    ( 4, 51, 70, 0.1345);

-- changeset script:15
-- comment: Creation asegurado
insert into asegurado (numero_identificacion, nombre, apellido, fecha_nacimiento, id_tipo_documento_pk, id_sexo_pk) values
    ( 79000001, 'APELLIDO1', 'NOMBRE1', '1945-01-10', 1, 1 ),
    ( 79000002, 'APELLIDO2', 'NOMBRE2', '1950-01-10', 1, 1 ),
    ( 79000003, 'APELLIDO3', 'NOMBRE3', '1955-01-10', 1, 1 ),
    ( 51000001, 'APELLIDO4', 'NOMBRE4', '1960-01-10', 2, 2 ),
    ( 51000002, 'APELLIDO5', 'NOMBRE5', '1965-01-10', 2, 2 ),
    ( 51000003, 'APELLIDO6', 'NOMBRE6', '1970-01-10', 2, 2 );